baseURL: https://nickybu.blog
languageCode: en-uk
title: Nicky Buttigieg
theme: "PaperMod"
paginate: 15

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

enableEmoji: true

taxonomies:
  tag: tags

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Nicky Buttigieg
  description: "A personal blog belonging to Nicky Buttigieg"
  keywords: [blog, nickybu, PaperMod]
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowFullTextinRSS: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.png"
    favicon16x16: "/favicon_16.png"
    favicon32x32: "/favicon_32.png"
    apple_touch_icon: "/favicon.png"
    safari_pinned_tab: "/favicon.png"

  label:
    text: "Nicky Buttigieg"
    icon:
    iconHeight: 0

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Nicky 👋🏻"
    Content: Oh hi this is a sample intro to see how the padding looks between this section and my posts. 

  socialIcons:
    - name: twitter
      url: "https://twitter.com/nickybu_"
    - name: github
      url: "https://github.com/nickybu"
    - name:
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/nickybu/nickybu.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  
  # search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 500
    threshold: 0.5
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: bookshelf
      name: bookshelf
      url: /bookshelf/
      weight: 20
    - identifier: rss
      name: rss
      pre: <i class='fa fa-rss'></i>
      url: /index.xml
      target: _blank
      weight: 40
    - identifier: search
      name: search
      pre: <i class='fa fa-search'></i>
      url: /search/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true # <- this enables HTML rendering
      xhtml: false
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

